---
title: "Make Roadway Assignment Viewer"
output: html_notebook
---


# Overhead
```{r overhead, include = FALSE}
packages_vector <- c("tidyverse",
                     "jsonlite",
                     "arrow",
                     "sf")

need_to_install <- packages_vector[!(packages_vector %in% installed.packages()[,"Package"])]

if (length(need_to_install)) install.packages(need_to_install)

for (package in packages_vector) {
  library(package, character.only = TRUE)
}

```

# Remote I/O
```{r remote-io}
data_dir <- "../../data/"
external_dir <- paste0(data_dir, "external/")
interim_dir <- paste0(data_dir, "interim/")
processed_dir <- paste0(data_dir, "processed/")

version <- "version_09"

links_file_name <- paste0(processed_dir, version, "/links.feather")
shape_file_name <- paste0(interim_dir, "simple_shape.RDS")
assigned_csv_prefix <- paste0(interim_dir, "loaded_net/new_net/", version, "/", "load")
legacy_assigned_csv_prefix <- paste0(interim_dir, "loaded_net/mtc_net/csv/", "load")

pems_match_file_name <- paste0(interim_dir, "pems_conflation_result.geojson")

conflation_file_name <- paste0(interim_dir, "conflation_result.csv")

output_file_name <- paste0(interim_dir, "roadway-assignment-viewer.geojson")
output_join_road_names <- paste0(interim_dir, "roadway-assignment-names-helper.csv")
```

# Parameters
```{r parameters}
ft_dict_df <- tibble(code = seq(0, 8),
                     label = c("Missing",
                               "Freeway",
                               "Expressway",
                               "Ramp",
                               "Divided Arterial",
                               "Undivided Arterial",
                               "Collector",
                               "Local",
                               "Centroid Connector"))

period_hours_df <- tibble(time_period = c("AM", "MD", "PM"),
                          hours = c(4L, 5L, 4L))

MANAGED_LANE_ID_OFFSET <- 10000000
```


# Data Reads
```{r read}
shapes_sf <- readRDS(shape_file_name)
links_df <- read_feather(links_file_name)
pems_df <- st_read(pems_match_file_name, stringsAsFactors = FALSE)
st_geometry(pems_df) <- NULL

conflation_df <- read_csv(conflation_file_name, col_types = cols(.default = col_character(),
                                                                 TM2_A = col_double(),
                                                                 TM2_B = col_double()))

loaded_df <- tibble()
for (period in c("AM", "MD", "PM")) {
  filename <- paste0(assigned_csv_prefix, period, ".csv")
  df <- read_csv(filename, col_types = cols(.default = col_double(),
                                            COUNTY = col_character(),
                                            SHSTGEOMETRYID = col_character(),
                                            CNTYPE = col_character()))
  
  period_hours <- filter(period_hours_df, time_period == period)$hours
  
  a_df <- df %>%
    rename(ml_lanes = matches(paste0("ML_LANES_", period))) %>%
    rename(lanes = matches(paste0("LANES_", period))) %>%
    select(model_link_id = MODEL_LINK_ID,
           feet = FEET,
           lanes,
           ft = FT,
           managed = MANAGED,
           segment_id = SEGMENT_ID,
           toll_booth = TOLLBOOTH,
           time = TIME_1,
           vc_ratio = VC_1,
           congested_speed = CSPD_1,
           volume = V_1) %>%
    mutate(distance = feet/5280.0) %>%
    select(-feet) %>%
    mutate(time_period = period) %>%
    mutate(vphpl = if_else(lanes > 0, volume / lanes / period_hours, 0.0))
  
  loaded_df <- bind_rows(loaded_df, a_df)
}

legacy_loaded_df <- tibble()
for (period in c("AM", "MD", "PM")) {
  filename <- paste0(legacy_assigned_csv_prefix, period, ".csv")
  df <- read_csv(filename, quote = "", col_types = cols(.default = col_double(),
                                                        NAME = col_character(),
                                                        TOLLRD = col_character(),
                                                        ONEWAY = col_character(),
                                                        CARRIAGE = col_character(),
                                                        CNTYPE = col_character(),
                                                        HIGHWAYT = col_character(),
                                                        PED_FLAG = col_character(),
                                                        RTEDIR = col_character()))
  
  period_hours <- filter(period_hours_df, time_period == period)$hours
  
  a_df <- df %>%
    rename(lanes = LANES) %>%
    select(A = OLD_A,
           B = OLD_B,
           lanes,
           time = TIME_1,
           vc_ratio = VC_1,
           congested_speed = CSPD_1,
           volume = V_1) %>%
    mutate(time_period = period) %>%
    mutate(vphpl = if_else(lanes > 0, volume / lanes / period_hours, 0.0))
  
  legacy_loaded_df <- bind_rows(legacy_loaded_df, a_df)
}

```

# Reductions 
```{r reductions}
# Lanes database
working_df <- links_df %>%
  filter(drive_access == 1) %>%
  select(model_link_id, lanes)

lanes_df <- working_df %>%
  filter(str_length(lanes) > 1) %>%
  separate(., lanes, into = c("default", "drop"), sep = ",", remove = FALSE, extra = "drop") %>%
  mutate(default_lanes = str_replace(default, "\\{'default': ", "")) %>%
  select(-lanes, -drop) %>%
  select(model_link_id, lanes = default_lanes) %>%
  bind_rows(., filter(working_df, str_length(lanes) == 1)) %>%
  mutate(lanes = as.integer(lanes))

remove(working_df)

# Names database
names_df <- links_df %>%
  filter(drive_access == 1) %>%
  select(model_link_id, name) %>%
  mutate(name = str_replace(name, "\\[", "")) %>%
  mutate(name = str_replace(name, "\\]", "")) %>%
  mutate(name = str_replace_all(name, "'", "")) %>%
  separate(name, 
           into = sprintf("%02d", seq(1:5)), 
           sep = ",",
           remove = TRUE,
           extra = "drop",
           fill = "right") %>%
  pivot_longer(cols = -c(model_link_id),
               names_to = "index",
               values_to = "name") %>%
  select(-index) %>%
  mutate(name = trimws(name)) %>%
  filter(!is.na(name)) %>%
  filter(name != "nan") %>%
  filter(name != "") %>%
  distinct(model_link_id, name) %>%
  group_by(model_link_id) %>%
  mutate(index = row_number()) %>%
  ungroup() %>%
  pivot_wider(id_cols = model_link_id,
              names_prefix = "name_",
              names_from = index,
              values_from = name) %>%
  mutate(name = if_else(is.na(name_2), name_1, paste0(name_1, "/", name_2))) %>%
  mutate(name = if_else(is.na(name_3), name, paste0(name, "/", name_3))) %>%
  mutate(simple_name = str_replace(name, " Avenue", "")) %>%
  mutate(simple_name = str_replace(simple_name, " Street", "")) %>%
  mutate(simple_name = str_replace(simple_name, " Drive", "")) %>%
  mutate(simple_name = str_replace(simple_name, " Boulevard", "")) %>%
  mutate(simple_name = str_replace(simple_name, " Way", "")) %>%
  select(model_link_id, name, simple_name)

distance_df <- loaded_df %>%
  distinct(model_link_id, distance)

pems_reduction_df <- pems_df %>%
  select(shstReferenceId, year, type, time_period, avg_flow, avg_speed) %>%
  filter(year %in% c(2014, 2015, 2016)) %>%
  group_by(shstReferenceId, type, time_period) %>%
  summarise(avg_flow = mean(avg_flow),
            avg_speed = mean(avg_speed), .groups = "drop") %>%
  group_by(shstReferenceId, time_period) %>%
  summarise(avg_flow = sum(avg_flow),
            avg_speed = sum(avg_speed), .groups = "drop") %>%
  rename(pems_volume = avg_flow, pems_speed = avg_speed) %>%
  pivot_longer(., cols = -c(shstReferenceId, time_period)) %>%
  mutate(name = paste0(time_period, "_", name)) %>%
  select(-time_period) %>%
  pivot_wider(., id_cols = c(shstReferenceId))

tm2_conflation_df <- conflation_df %>%
  filter(!is.na(TM2_A)) %>%
  select(shstReferenceId, A = TM2_A, B = TM2_B)

legacy_df <- legacy_loaded_df %>%
  inner_join(tm2_conflation_df, by = c("A", "B")) %>%
  select(-lanes, -A, -B) %>%
  rename(legacy_volume = volume, legacy_time = time, legacy_vc_ratio = vc_ratio, legacy_congested_speed = congested_speed, legacy_vphpl = vphpl) %>%
  pivot_longer(., cols = -c(shstReferenceId, time_period)) %>%
  mutate(name = paste0(time_period, "_", name)) %>%
  select(-time_period) %>%
  pivot_wider(., id_cols = c(shstReferenceId))

managed_df <- loaded_df %>%
  filter(managed == 1) %>%
  mutate(model_link_id = model_link_id - MANAGED_LANE_ID_OFFSET) %>%
  select(model_link_id,
         time_period,
         segment_id,
         number_of_managed_lanes = lanes,
         managed_lane_volume = volume,
         managed_lane_time = time,
         managed_lane_vc_ratio = vc_ratio,
         managed_lane_congested_speed = congested_speed)

working_df <- loaded_df %>%
  filter(managed == 0) %>%
  select(-distance) %>%
  left_join(., managed_df, by = c("model_link_id", "segment_id", "time_period")) %>%
  mutate(volume = if_else(is.na(managed_lane_volume), volume, volume + managed_lane_volume)) %>%
  mutate(lanes = if_else(is.na(number_of_managed_lanes), lanes, lanes + number_of_managed_lanes)) %>%
  pivot_longer(., cols = -c(model_link_id, time_period, segment_id)) %>%
  mutate(name = paste0(time_period, "_", name)) %>%
  select(-time_period) %>%
  pivot_wider(., id_cols = c(model_link_id, segment_id)) %>%
  left_join(., ft_dict_df, by = c("AM_ft" = "code")) %>%
  rename(AM_ft_label = label) %>%
  left_join(., ft_dict_df, by = c("MD_ft" = "code")) %>%
  rename(MD_ft_label = label) %>%
  left_join(., ft_dict_df, by = c("PM_ft" = "code")) %>%
  rename(PM_ft_label = label)
  
ft_to_keep_vector <- c("Freeway", "Expressway", "Ramp", "Divided Arterial", "Undivided Arterial")
output_sf <- links_df %>%
  filter(drive_access == 1) %>%
  select(shstReferenceId, shape_id, model_link_id, county) %>%
  mutate(shape_id = as.integer(shape_id)) %>%
  left_join(., working_df, by = c("model_link_id")) %>%
  left_join(., lanes_df, by = c("model_link_id")) %>%
  left_join(., names_df, by = c("model_link_id")) %>%
  left_join(., pems_reduction_df, by = c("shstReferenceId")) %>%
  left_join(., legacy_df, by = c("shstReferenceId")) %>%
  left_join(., distance_df, by = c("model_link_id")) %>%
  filter(AM_ft_label %in% ft_to_keep_vector | 
           PM_ft_label %in% ft_to_keep_vector |
           AM_toll_booth < 10 |
           PM_toll_booth < 10
        ) %>%
    left_join(., shapes_sf, by = c("shape_id"))

```

# Write
```{r write}
st_write(output_sf, output_file_name, delete_dsn = TRUE)
```

# Debug
```{r}
vector <- c(8063198, 8063199, 3315451, 3315452)

o_sf <- output_sf %>%
  filter(model_link_id %in% vector)

l_df <- links_df %>%
  filter(model_link_id %in% vector)


  
```

