---
title: "Make Shape RDS"
output:
  html_document:
    df_print: paged
---


# Overhead
```{r overhead, include = FALSE}
packages_vector <- c("tidyverse",
                     "sf")

need_to_install <- packages_vector[!(packages_vector %in% installed.packages()[,"Package"])]

if (length(need_to_install)) install.packages(need_to_install)

for (package in packages_vector) {
  library(package, character.only = TRUE)
}

```

# Remote I/O
```{r remote-io}
USERPROFILE    <- Sys.getenv("USERPROFILE")
USERPROFILE    <- str_replace_all(USERPROFILE, "\\\\","/")
BOX_DATA_DIR   <- paste0(USERPROFILE, 
                         "/Box/Modeling and Surveys/Development/Travel Model Two Development",
                         "/Travel Model Two Network Rebuild/travel-model-two-networks/data")
VERSION        <- "12"
processed_dir  <- file.path(BOX_DATA_DIR, "processed")
interim_dir    <- file.path(BOX_DATA_DIR, "interim")

shape_file_name  <- file.path(processed_dir, paste0("version_",VERSION), "network_standard",
                              paste0("v",VERSION,"_shape.geojson"))
output_file_name <- file.path(interim_dir, "simple_shape.RDS")
```

# Data Reads
```{r read}
shapes_sf <- st_read(shape_file_name)
```

# Reductions 
```{r reductions}
output_sf <- shapes_sf %>%
  select(id, geometry)
```

# Write
```{r write}
saveRDS(output_sf, file = output_file_name)
```

