---
title: "Make Pretty Transit Viewer"
output:
  html_document:
    df_print: paged
---

# Overhead
```{r overhead, include = FALSE}
packages_vector <- c("tidyverse",
                     "arrow",
                     "lubridate",
                     "sf")

need_to_install <- packages_vector[!(packages_vector %in% installed.packages()[,"Package"])]

if (length(need_to_install)) install.packages(need_to_install)

for (package in packages_vector) {
  library(package, character.only = TRUE)
}

```

# Remote I/O
```{r remote-io}
USERPROFILE    <- Sys.getenv("USERPROFILE")
USERPROFILE    <- str_replace_all(USERPROFILE, "\\\\","/")
BOX_DATA_DIR   <- paste0(USERPROFILE, 
                         "/Box/Modeling and Surveys/Development/Travel Model Two Development",
                         "/Travel Model Two Network Rebuild/travel-model-two-networks/data")
VERSION        <- "12"

processed_dir        <- file.path(BOX_DATA_DIR, "processed")
interim_dir          <- file.path(BOX_DATA_DIR, "interim")
standard_version_dir <- file.path(processed_dir, paste0("version_",VERSION), "network_standard")

# Input files
shape_file_name      <- file.path(interim_dir, "simple_shape.RDS") # see make-shape-rds.Rmd
links_file_name      <- file.path(standard_version_dir, paste0("v",VERSION,"_links.feather"))
node_file_name       <- file.path(standard_version_dir, paste0("v",VERSION,"_node.geojson"))

# Ouput files
output_file_name     <- file.path(interim_dir, "transit_for_tableau.geojson")
```

# Data Reads
```{r read}
routes_df     <- read_csv(file.path(standard_version_dir, paste0("v",VERSION,"_routes.txt")), 
                          col_types = cols(.default = col_character()))
freq_df       <- read_csv(file.path(standard_version_dir, paste0("v",VERSION,"_frequencies.txt")),
                          col_types = cols(.default = col_character()))
trips_df      <- read_csv(file.path(standard_version_dir, paste0("v",VERSION,"_trips.txt")),
                          col_types = cols(.default = col_character()))
stops_df      <- read_csv(file.path(standard_version_dir, paste0("v",VERSION,"_stops.txt")),
                          col_types = cols(.default = col_character()))
shapes_df     <- read_csv(file.path(standard_version_dir, paste0("v",VERSION,"_shapes.txt")),
                          col_types = cols(.default = col_character()))
stop_times_df <- read_csv(file.path(standard_version_dir, paste0("v",VERSION,"_stop_times.txt")),
                          col_types = cols(.default = col_character()))

links_df  <- read_feather(links_file_name)
shapes_sf <- readRDS(shape_file_name)
nodes_sf  <- st_read(node_file_name)
```

# Helpers
```{r helpers}
shape_as_sf_linestring <- function(df) {
  # as suggested by www.github.com/mdsumner via tidytransit
  
  df <- df[[1]]
  m <- as.matrix(df[order(df$shape_pt_sequence),
                    c("lat", "lng")])

  return(sf::st_linestring(m))
}
```


# Make True Shapes of Segments
```{r process-shapes}
join_link_shape_sf <- links_df %>%
  select(shstGeometryId, A, B) %>%
  left_join(., shapes_sf, by = c("shstGeometryId" = "id"))

working_df <- select(routes_df, agency_id, agency_raw_name, route_id, 
                           route_short_name, route_long_name) %>%
  left_join(select(trips_df, route_id, service_id, trip_id, trip_headsign, direction_id, shape_id),
            ., by = c("route_id")) %>%
  left_join(., freq_df, by = c("trip_id")) %>%
  left_join(., 
            select(shapes_df, shape_id, shape_pt_sequence, shape_model_node_id), 
            by = c("shape_id")) %>%
  group_by(route_id, service_id, trip_id, direction_id) %>%
  mutate(join_A = as.integer(shape_model_node_id)) %>%
  mutate(join_B = as.integer(lead(shape_model_node_id))) %>%
  ungroup() %>%
  filter(!is.na(join_B)) %>%
  left_join(., join_link_shape_sf, by = c("join_A" = "A", "join_B" = "B")) %>%
  mutate(start_time = as.integer(as.double(start_time) / 60.0 / 60.0)) %>%
  mutate(time_period = case_when(
    start_time == 3 ~ "Early Morning",
    start_time == 6 ~ "Morning Commute",
    start_time == 10 ~ "Midday",
    start_time == 15 ~ "Evening Commute",
    start_time == 19 ~ "Evening/Night",
    TRUE ~ "Missing"
  )) %>%
  select(-start_time, -end_time)

# make lat/lng for points
working_points_sf <- working_df %>%
  st_as_sf(., crs = 4326) %>%
  st_cast(., to = "POINT", group_or_split = TRUE, do_split = TRUE, warn = FALSE)

lat_lng_df <- as_tibble(st_coordinates(working_points_sf)) %>%
  rename(lng = Y, lat = X)

working_df <- working_points_sf %>%
  select(agency_id, agency_raw_name, route_id, route_short_name, route_long_name,
           trip_id, service_id, trip_headsign, direction_id, shape_id,
           time_period, headway_secs) %>%
  bind_cols(., lat_lng_df) %>%
  st_drop_geometry(.) %>%
  group_by(agency_id, route_id, time_period, direction_id, shape_id) %>%
  mutate(shape_pt_sequence = row_number()) %>%
  ungroup() 

for_shapes_df <- working_df %>%
  mutate(unique_id = row_number()) %>%
  select(unique_id, shape_id, shape_pt_sequence, lat, lng)

list_of_line_tibbles <- split(for_shapes_df, for_shapes_df$shape_id)

list_of_linestrings <- list()
for (index in seq(1:length(list_of_line_tibbles))) {

  line_tibble <- list_of_line_tibbles[index]
  list_of_linestrings[[index]] <- shape_as_sf_linestring(line_tibble)
  
}

shape_linestrings <- sf::st_sfc(list_of_linestrings, crs = 4326)
shapes_sf <- sf::st_sf(shape_id = names(list_of_line_tibbles), geometry = shape_linestrings) %>%
  mutate(shape_id = as.integer(shape_id))

join_df <- working_df %>%
  distinct(agency_id, agency_raw_name, route_id, route_short_name, route_long_name,
           trip_id, service_id, trip_headsign, direction_id, shape_id,
           time_period, headway_secs) %>%
  mutate(shape_id = as.integer(shape_id))

output_sf <- left_join(shapes_sf, join_df, by = c("shape_id"))

```

# Write
```{r write}
st_write(output_sf, output_file_name, delete_dsn = TRUE)
```

