---
title: "Look at All Network"
output: html_notebook
---

# Overhead
```{r overhead, include = FALSE}
packages_vector <- c("tidyverse",
                     "sf")

need_to_install <- packages_vector[!(packages_vector %in% installed.packages()[,"Package"])]

if (length(need_to_install)) install.packages(need_to_install)

for (package in packages_vector) {
  library(package, character.only = TRUE)
}

```

# Remote I/O
```{r remote-io}
interim_dir <- "../../data/interim/"
processed_dir <- "../../data/processed/" 

output_file_name <- paste0(interim_dir, "transit_for_tableau.csv")
```

# Parameters
```{r parameters}
VERSION <- "version_09"
```


# Data Reads
```{r read}
routes_df <- read_csv(paste0(processed_dir, VERSION, "/routes.txt"), col_types = "ccccciccccccccci")
freq_df <- read_csv(paste0(processed_dir, VERSION, "/frequencies.txt"), col_types = "iidd")
trips_df <- read_csv(paste0(processed_dir, VERSION, "/trips.txt"), col_types = "ccncnncccccccccccciii")
stops_df <- read_csv(paste0(processed_dir, VERSION, "/stops.txt"), col_types  = "ccddccnccnccccinci")
shapes_df <- read_csv(paste0(processed_dir, VERSION, "/shapes.txt"), col_types = "iincidd")
stop_times_df <- read_csv(paste0(processed_dir, VERSION, "/stop_times.txt"), col_types = cols(.default = col_character(),
                                                                                              arrival_time = col_double(),
                                                                                              departure_time = col_double(),
                                                                                              stop_sequence = col_integer(),
                                                                                              timepoint = col_double(),
                                                                                              trip_id = col_integer(),
                                                                                              stop_id = col_integer()))

nodes_sf <- st_read(paste0(processed_dir, VERSION, "/node.geojson"))
```

# Reductions for TM Network
```{r reductions}
nodes_df <- bind_cols(tibble(model_node_id = nodes_sf$model_node_id), as_tibble(st_coordinates(nodes_sf))) %>%
  rename(lng = X, lat = Y)

output_stops_df <- select(routes_df, route_id_original, route_id, agency_id, route_short_name, route_long_name, agency_raw_name) %>%
  left_join(select(trips_df, route_id, service_id, trip_id, trip_headsign, direction_id, shape_id),
            ., by = c("route_id")) %>%
  left_join(., freq_df, by = c("trip_id")) %>%
  left_join(select(stop_times_df, trip_id, stop_id, stop_sequence), ., by = c("trip_id")) %>%
  left_join(., select(stops_df, stop_id, stop_name, stop_lat, stop_lon), by = c("stop_id")) %>%
  mutate(summary = "stops")

output_shapes_df <- select(routes_df, route_id_original, route_id, agency_id, route_short_name, route_long_name, agency_raw_name) %>%
  left_join(select(trips_df, route_id, service_id, trip_id, trip_headsign, direction_id, shape_id),
            ., by = c("route_id")) %>%
  left_join(., freq_df, by = c("trip_id")) %>%
  left_join(., select(shapes_df, shape_id, shape_pt_sequence, shape_model_node_id), by = c("shape_id")) %>%
  left_join(., nodes_df, by = c("shape_model_node_id" = "model_node_id")) %>%
  mutate(summary = "shapes")

output_df <- bind_rows(output_stops_df, output_shapes_df)

```

# Write
```{r write}
write_csv(output_df, path = output_file_name, na = "")
```

