---
title: "Make Facility Type Viewer"
output: html_notebook
---


# Overhead
```{r overhead, include = FALSE}
packages_vector <- c("tidyverse",
                     "tidyselect",
                     "arrow",
                     "sf",
                     "stringdist")

need_to_install <- packages_vector[!(packages_vector %in% installed.packages()[,"Package"])]

if (length(need_to_install)) install.packages(need_to_install)

for (package in packages_vector) {
  library(package, character.only = TRUE)
}

```

# Remote I/O
```{r remote-io}
external_dir <- "../../data/external/"
interim_dir <- "../../data/interim/"
processed_dir <- "../../data/processed/" 

managed_file_name <- paste0(interim_dir, "Managed_Lanes_Database.csv")

links_file_name <- paste0(interim_dir, "step5_tidy_roadway/link.feather")
shape_file_name <- paste0(interim_dir, "simple_shape.RDS")

output_file_name <- paste0(interim_dir, "managed-lane-viewer.geojson")
corrected_managed_file_name <- paste0(interim_dir, "Corrected_Managed_Lanes_Database.csv")
```

# Parameters
```{r parameters}

```


# Data Reads
```{r read}
shapes_sf <- readRDS(shape_file_name)
links_df <- read_feather(links_file_name)
managed_df <- read_csv(managed_file_name, col_types = cols(.default = col_character()))
```

# Edits to Managed Lane Database
```{r edits}
managed_out_df <- managed_df %>%
  filter(!(shstReferenceId == "7bb59b6716c8d22b38f90e1696461e5e" & roadType == "HOV_Lane")) %>%
  filter(!(shstReferenceId == "a1be9886a94386cc8d028bfd5a076ba4" & roadType == "HOV_Lane")) %>%
  filter(!(shstReferenceId == "d35424123c61127fcb906140f2e14b61" & roadType == "HOV_Lane")) %>%
  filter(!(shstReferenceId == "42540cb7ed261fa5074bc659ba8caee2" & roadType == "HOV_Lane")) %>%
  filter(!(shstReferenceId == "44745ac6ebae7a5b78ba6c4bccc43b68")) %>%
  filter(!(shstReferenceId == "e5bab32b8697116f3e53cb25c1d897ac")) %>%
  filter(!(shstReferenceId == "9b89a5f78a4058d7c24bc96a351c5e60")) %>%
  filter(!(shstReferenceId == "1cbd597fa3a1fc54f1b4fb75986723f5")) %>%
  filter(!(shstReferenceId == "bf39e14aed29a2d0277570f83acd46ff")) %>%
  filter(!(shstReferenceId == "3164f8f9abcc0f0a37c58e0577c86bdf")) %>%
  filter(!(shstReferenceId == "ce62845676152cf9a24d1736f87d1872")) %>%
  filter(!(shstReferenceId == "f3ae9a25daead7857d58cecad6b66791")) %>%
  filter(!(shstReferenceId == "7c9b616f34bb6c8961d3ad3c092e91a5")) %>%
  filter(!(shstReferenceId == "4e570e4d6b3e00ac9fb9af5808e8f2d3")) %>%
  filter(!(shstReferenceId == "31d8141c11d31010cb8d85b9f33cee12")) %>%
  filter(!(shstReferenceId == "098a555a49342b0361bf73d4fb145628")) %>%
  filter(!(shstReferenceId == "2896efadc3673a041b5533fed1597f53")) %>%
  filter(!(shstReferenceId == "5cb208be89de29c545b615a215e3b03d")) %>%
  filter(!(shstReferenceId == "e0f8a9be8f36933b93e37c4034dbb282")) %>%
  filter(!(shstReferenceId == "14f8d24d1190890fbbdfe5c0a8bb35fe")) %>%
  mutate(roadName = if_else(shstReferenceId == "541fc68091b15d8682c6b398e990af64", "Antioch Bridge", roadName)) %>%
  mutate(roadType = if_else(shstReferenceId == "541fc68091b15d8682c6b398e990af64", "Bridge_Pass", roadType)) %>%
  mutate(roadType = if_else(shstReferenceId == "f30dcff458c14bb7c63f6a6b7ecf4fb6", as.character(NA), roadType)) %>%
  mutate(bridge_detail = as.character(NA)) %>%
  mutate(bridge_detail = if_else(shstReferenceId == "42540cb7ed261fa5074bc659ba8caee2", "Benicia Bridge HOV", bridge_detail)) %>%
  mutate(bridge_detail = if_else(shstReferenceId == "217253518a29aa69c40a4114d557d24d", "Benicia General Purpose", bridge_detail)) %>%
  mutate(bridge_detail = if_else(shstReferenceId == "44e88bf3d040195167b31388d839122e", "Benicia Fastrak", bridge_detail)) %>%
  mutate(bridge_detail = if_else(shstReferenceId == "a1be9886a94386cc8d028bfd5a076ba4", "Bay Bridge HOV", bridge_detail)) %>%
  mutate(bridge_detail = if_else(shstReferenceId == "f30dcff458c14bb7c63f6a6b7ecf4fb6", "Bay Bridge HOV", bridge_detail)) %>%
  mutate(bridge_detail = if_else(shstReferenceId == "d35424123c61127fcb906140f2e14b61", "Bay Bridge HOV", bridge_detail)) %>%
  bind_rows(., 
            tibble(shstReferenceId = c("d35424123c61127fcb906140f2e14b61",
                                       "4e570e4d6b3e00ac9fb9af5808e8f2d3",
                                       "541fc68091b15d8682c6b398e990af64",
                                       "e8a712ba58f30c910ff65a46eb6b605e",
                                       "44745ac6ebae7a5b78ba6c4bccc43b68",
                                       "e5bab32b8697116f3e53cb25c1d897ac"),
                   bridge_detail = c("Bay Bridge HOV",
                                     "Bay Bridge General Purpose",
                                     "Antioch Bridge",
                                     "Richmond Bridge",
                                     "Benicia Bridge HOV",
                                     "Benicia Bridge HOV"),
                   roadType = c(as.character(NA),
                                "Bridge_Pass",
                                "Bridge_Pass",
                                "Bridge_Pass",
                                as.character(NA),
                                as.character(NA))))
  
```


# Reductions 
```{r reductions}
managed_join_df <- select(managed_out_df, 
                          shstReferenceId, 
                          roadType, 
                          tomtom_name,
                          bridge_detail) %>%
  mutate(make_parallel_hov = (roadType == "HOV_Lane")) %>%
  mutate(pay_bridge_toll = (roadType == "Bridge_Pass")) %>%
  mutate(make_parallel_express = (roadType == "Express_Lane")) %>%
  group_by(shstReferenceId, tomtom_name) %>%
  summarise(pay_bridge_toll = max(pay_bridge_toll),
            make_parallel_hov = max(make_parallel_hov),
            make_parallel_express = max(make_parallel_express),
            bridge_detail = max(bridge_detail)) %>%
  ungroup()

output_sf <- links_df %>%
  select(shstReferenceId, shstGeometryId, roadway) %>%
  filter(roadway %in% c("motorway", "motorway_link", "trunk", "trunk_link")) %>% 
  left_join(., managed_join_df, by = c("shstReferenceId")) %>%
  left_join(., shapes_sf, by = c("shstGeometryId"))

```

# Write
```{r write}
st_write(output_sf, output_file_name, delete_dsn = TRUE)
write_csv(managed_out_df, path = corrected_managed_file_name)
```


