---
title: "Summarize Transit Assignment"
output: html_notebook
---

# Overhead
```{r overhead, include = FALSE}
packages_vector <- c( "tidyverse")

need_to_install <-
  packages_vector[!(packages_vector %in% installed.packages()[, "Package"])]

if (length(need_to_install)) install.packages(need_to_install)

for (package in packages_vector) {
  library(package, character.only = TRUE)
}

```

# Remote I/O
```{r remote-io}
interim_dir <- "../../data/interim/"
processed_dir <- "../../data/processed/"

input_assignment_outcomes <- paste0(interim_dir, "boarding_by_route_and_period.csv")
input_route_file <- paste0(processed_dir, "version_03/routes.txt")

output_file_name <- paste0(interim_dir, "transit-assignment-tableau.csv")

```

# Parameters
```{r parameters}
agency_name_map <- tibble(gtfs_file = c("ACTransit_2015_8_14",
                                        "BART_2015_8_3",
                                        "CCTA_2015_8_11",
                                        "Emeryville_2016_10_26",
                                        "Fairfield_2015_10_14",
                                        "GGTransit_2015_9_3",
                                        "Marguerite_2016_10_10",
                                        "MarinTransit_2015_8_31",
                                        "MVGo_2016_10_26",
                                        "petalumatransit-petaluma-ca-us__11_12_15",
                                        "RioVista_2015_8_20",
                                        "SamTrans_2015_8_20",
                                        "SantaRosa_google_transit_08_28_15",
                                        "SFMTA_2015_8_11",
                                        "Soltrans_2016_5_20",
                                        "SonomaCounty_2015_8_18",
                                        "TriDelta-GTFS-2018-05-24_21-43-17",
                                        "Union_City_Transit_Aug-01-2015 to Jun-30-2017",
                                        "vacavillecitycoach-2020-ca-us",
                                        "Vine_GTFS_PLUS_2015",
                                        "VTA_2015_8_27",
                                        "westcat-ca-us_9_17_2015",
                                        "Wheels_2016_7_13"),
                          agency_name = c("AC Transit",
                                          "BART",
                                          "County Connection",
                                          "Emery-go-round",
                                          "Fairfield",
                                          "Golden Gate Transit",
                                          "Stanford Marguerite",
                                          "Marin Transit",
                                          "Mountain View GO",
                                          "Petaluma",
                                          "Rio Vista",
                                          "SamTrans",
                                          "Santa Rosa CityBus",
                                          "SF Muni",
                                          "Soltrans",
                                          "Sonoma County",
                                          "Tri-Delta",
                                          "Union City",
                                          "Vacaville",
                                          "Vine",
                                          "VTA",
                                          "WestCat",
                                          "LAVTA Wheels"))
```

# Data Reads
```{r data-reads}
routes_df <- read_csv(input_route_file, col_types = cols(.default = col_character(),
                                                         route_type = col_integer(),
                                                         route_sort_order = col_integer(),
                                                         min_headway_minutes = col_double()))

assign_df <- read_csv(input_assignment_outcomes, col_types = cols(.default = col_character(),
                                                                  boardings = col_double()))
```

# Reductions
```{r reductions}
join_df <- routes_df %>%
  select(route_id, route_short_name, route_long_name, gtfs_file = agency_raw_name) %>%
  left_join(., agency_name_map, by = c("gtfs_file"))

output_df <- assign_df %>%
  separate(., route_name, 
           into = c("agency_id", "route_id", "tod_name", "direction", "shp_id"),
           sep = "_",
           remove = FALSE,
           extra = "warn") %>%
  left_join(., join_df, by = c("route_id")) %>%
  select(-tod_name)
```

# Write to Disk
```{r data-write}
write_csv(output_df, path = output_file_name)
```


