;
; For testing -- Adds TOLLBOOTH=25 to a number of links to test value tolls.
; 
; Input:  hwy\mtc_final_network.net
; Output: hwy\mtc_final_network.net

RUN PGM=HWYNET
    PAR NODES=10000000
    NETI = hwy\mtc_final_network.net
    NETO = hwy\mtc_final_network_tb25.net
    IF ((A = 7079063) & (B = 7050993))
        TOLLBOOTH = 25
        _LINKS_FOUND = _LINKS_FOUND + 1
    ELSEIF ((A = 7050993) & (B = 7057151))
        TOLLBOOTH = 25
        _LINKS_FOUND = _LINKS_FOUND + 1
    ELSEIF ((A = 7057151) & (B = 7088202))
        TOLLBOOTH = 25
        _LINKS_FOUND = _LINKS_FOUND + 1
    ELSEIF ((A = 7088202) & (B = 7077888))
        TOLLBOOTH = 25
        _LINKS_FOUND = _LINKS_FOUND + 1
    ELSEIF ((A = 7077888) & (B = 7051005))
        TOLLBOOTH = 25
        _LINKS_FOUND = _LINKS_FOUND + 1
    ELSEIF ((A = 7051005) & (B = 7077417))
        TOLLBOOTH = 25
        _LINKS_FOUND = _LINKS_FOUND + 1
    ELSEIF ((A = 7077417) & (B = 7050029))
        TOLLBOOTH = 25
        _LINKS_FOUND = _LINKS_FOUND + 1
    ELSEIF ((A = 7050029) & (B = 7006291))
        TOLLBOOTH = 25
        _LINKS_FOUND = _LINKS_FOUND + 1
    ELSEIF ((A = 7006291) & (B = 7050713))
        TOLLBOOTH = 25
        _LINKS_FOUND = _LINKS_FOUND + 1
    ELSEIF ((A = 7050713) & (B = 7059489))
        TOLLBOOTH = 25
        _LINKS_FOUND = _LINKS_FOUND + 1
    ELSEIF ((A = 7059489) & (B = 7078415))
        TOLLBOOTH = 25
        _LINKS_FOUND = _LINKS_FOUND + 1
    ELSEIF ((A = 7078415) & (B = 7056619))
        TOLLBOOTH = 25
        _LINKS_FOUND = _LINKS_FOUND + 1
    ELSEIF ((A = 7056619) & (B = 7090598))
        TOLLBOOTH = 25
        _LINKS_FOUND = _LINKS_FOUND + 1
    ELSEIF ((A = 7090598) & (B = 7059061))
        TOLLBOOTH = 25
        _LINKS_FOUND = _LINKS_FOUND + 1
    ELSEIF ((A = 7059061) & (B = 7011967))
        TOLLBOOTH = 25
        _LINKS_FOUND = _LINKS_FOUND + 1
    ELSEIF ((A = 7011967) & (B = 7085853))
        TOLLBOOTH = 25
        _LINKS_FOUND = _LINKS_FOUND + 1
    ENDIF

    PHASE=SUMMARY
        PRINT LIST="Updated ",_LINKS_FOUND," links to TOLLBOTH=25."
        IF (_LINKS_FOUND < 16) ABORT MSG="Didn't find all the TOLLBOOTH=25 links."
    ENDPHASE
ENDRUN

*copy hwy\mtc_final_network_tb25.net hwy\mtc_final_network.net